/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.klenze_kk.lingling.Gui;
import de.klenze_kk.lingling.Main;

/**
 *
 * @author andriy
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
      // username.setText(Main.getUser().name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        home = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        games = new javax.swing.JButton();
        vokabeln = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        statistics = new javax.swing.JButton();
        username = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(127, 600));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        UserLabel.setText("Nutzer:");

        games.setBackground(new java.awt.Color(255, 51, 51));
        games.setForeground(new java.awt.Color(255, 255, 255));
        games.setText("Games");
        games.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamesActionPerformed(evt);
            }
        });

        vokabeln.setBackground(new java.awt.Color(0, 204, 0));
        vokabeln.setForeground(new java.awt.Color(255, 255, 255));
        vokabeln.setText("Vokabeln");
        vokabeln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vokabelnActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(0, 0, 0));
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log-Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        statistics.setBackground(new java.awt.Color(0, 153, 153));
        statistics.setForeground(new java.awt.Color(255, 255, 255));
        statistics.setText("Vokabel-Sets");
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });

        username.setText("Jlabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vokabeln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(games, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserLabel)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(UserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(vokabeln)
                .addGap(31, 31, 31)
                .addComponent(games)
                .addGap(33, 33, 33)
                .addComponent(statistics)
                .addGap(186, 186, 186)
                .addComponent(home)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>                        

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {                                     
      Main.setJPanel(new Hub());
    }                                    

    private void gamesActionPerformed(java.awt.event.ActionEvent evt) {                                      
       Main.setJPanel(new MiniGameHub());
    }                                     

    private void vokabelnActionPerformed(java.awt.event.ActionEvent evt) {                                         
      Main.setJPanel(new Vokabeln());
    }                                        

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Main.logOut();
    }                                      

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {                                           
       Main.setJPanel(new VokabelSet());
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JLabel UserLabel;
    private javax.swing.JButton games;
    private javax.swing.JButton home;
    private javax.swing.JButton logOut;
    private javax.swing.JButton statistics;
    private javax.swing.JLabel username;
    private javax.swing.JButton vokabeln;
    // End of variables declaration                   
}
