/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.klenze_kk.lingling.Gui;

import de.klenze_kk.lingling.Main;

/**
 *
 * @author andriy
 */
public class Hub extends javax.swing.JPanel {

    /**
     * Creates new form Hub
     */
    public Hub() {
        initComponents();
        //userName.setText(Main.getUser().name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        miniGameHub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vokabeln = new javax.swing.JButton();
        statistik = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        nutzer = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        miniGameHub.setBackground(new java.awt.Color(255, 51, 51));
        miniGameHub.setForeground(new java.awt.Color(255, 255, 255));
        miniGameHub.setText("Minigamehub");
        miniGameHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniGameHubActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setText("ling ling");

        vokabeln.setBackground(new java.awt.Color(0, 204, 0));
        vokabeln.setForeground(new java.awt.Color(255, 255, 255));
        vokabeln.setText("Vokabeln");
        vokabeln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vokabelnActionPerformed(evt);
            }
        });

        statistik.setBackground(new java.awt.Color(0, 153, 153));
        statistik.setForeground(new java.awt.Color(255, 255, 255));
        statistik.setText("Vokabel-Sets");
        statistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistikActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(0, 0, 0));
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log-Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        nutzer.setText("Nutzer:");

        userName.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(miniGameHub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vokabeln, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statistik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutzer)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miniGameHub, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statistik, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vokabeln, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(nutzer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>                        

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Main.logOut();
    }                                      

    private void vokabelnActionPerformed(java.awt.event.ActionEvent evt) {                                         
  Main.setJPanel(new Vokabeln());
    }                                        

    private void miniGameHubActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Main.setJPanel(new MiniGameHub());
    }                                           

    private void statistikActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Main.setJPanel(new VokabelSet());
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton miniGameHub;
    private javax.swing.JLabel nutzer;
    private javax.swing.JButton statistik;
    private javax.swing.JLabel userName;
    private javax.swing.JButton vokabeln;
    // End of variables declaration                   
}
