/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.klenze_kk.lingling.Gui;
import de.klenze_kk.lingling.Main;
import javax.swing.JPanel;
import java.util.Set;
import de.klenze_kk.lingling.logic.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;


public class PresentationPanel extends javax.swing.JPanel{

    JPanel previousPanel;
    VocabularyPresentation vp;
    /**
     * Creates new form PresentationPanel
     */
    public PresentationPanel(Set<Vocabulary> v, JPanel previousPanel) {
        initComponents();
        this.previousPanel = previousPanel;
        vp = VocabularyPresentation.present(this, new ArrayList<>(v));
        von.setText(" / " + String.valueOf(v.size()));
        aktuell.addKeyListener(new KeyListener() {
            
            int size = v.size();
            
            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() != KeyEvent.VK_ENTER)
                    return;
                int text;
               
                try{
                   text = Integer.parseInt(aktuell.getText());
               }catch(NumberFormatException c){
                   Main.handleError("Die Eingabe ist keine Zahl!!!", false);
                   return;
               }
                if(text<1 || text > size){
                    Main.handleError("Absurde Zahlen verboten!!!", false);
                    return;
                }
                vp.setCursor(text-1);
            }

            @Override
            public void keyReleased(KeyEvent e) {
               
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        controlPanel1 = new de.klenze_kk.lingling.Gui.ControlPanel();
        zurueck = new javax.swing.JButton();
        abbrechen = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deutsch = new javax.swing.JLabel();
        chinesisch = new javax.swing.JLabel();
        pinyin = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        von = new javax.swing.JLabel();
        aktuell = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        zurueck.setBackground(new java.awt.Color(204, 0, 204));
        zurueck.setForeground(new java.awt.Color(255, 255, 255));
        zurueck.setText("zurueck");
        zurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurueckActionPerformed(evt);
            }
        });

        abbrechen.setBackground(new java.awt.Color(255, 0, 0));
        abbrechen.setForeground(new java.awt.Color(255, 255, 255));
        abbrechen.setText("abbrechen");
        abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrechenActionPerformed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(255, 153, 0));
        pause.setForeground(new java.awt.Color(255, 255, 255));
        pause.setText("pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(0, 204, 51));
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Zeichen: ");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Deutsch:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("pinyin:");

        deutsch.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        deutsch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deutsch.setText("Deutsch");

        chinesisch.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        chinesisch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chinesisch.setText("Zeichen");

        pinyin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        pinyin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pinyin.setText("Pinyin");

        von.setText("von");

        aktuell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aktuell.setText("aktuell");
        aktuell.setToolTipText("");
        aktuell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(controlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aktuell, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(von)))
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deutsch)
                            .addComponent(chinesisch)
                            .addComponent(pinyin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(abbrechen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(zurueck)
                        .addGap(46, 46, 46)
                        .addComponent(pause)
                        .addGap(55, 55, 55)
                        .addComponent(next)
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(controlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(chinesisch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pinyin))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deutsch))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(von)
                        .addComponent(aktuell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pause)
                    .addComponent(next)
                    .addComponent(zurueck)
                    .addComponent(abbrechen))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>                        

    private void zurueckActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
        vp.moveCursorManually(false);    
        } catch (Exception e) {
        }
        
    }                                       

    
    private void abbrechenActionPerformed(java.awt.event.ActionEvent evt) {                                          
        vp.cancel();
    }                                         

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {                                      
       boolean isPaused = !vp.isPaused();
       pause.setText(isPaused ? "fortsetzen" : "pause");
       vp.setPaused(isPaused);
       
    }                                     

    public void updateProgress(double prozent){
        progress.setValue((int) (prozent*100));
    }
    
    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        try {
        vp.moveCursorManually(true);    
        } catch (Exception e) {
        }
        
    }                                    

    public void setCurrentVoc(Vocabulary v){
        chinesisch.setText(v.chinese);
        pinyin.setText(v.pinyin);
        deutsch.setText(v.translation);
        aktuell.setText(String.valueOf(vp.getCursor()+1));
    }

    public void presentationIsOver(){
        Main.setJPanel(previousPanel);
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton abbrechen;
    private javax.swing.JTextField aktuell;
    private javax.swing.JLabel chinesisch;
    private de.klenze_kk.lingling.Gui.ControlPanel controlPanel1;
    private javax.swing.JLabel deutsch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton next;
    private javax.swing.JButton pause;
    private javax.swing.JLabel pinyin;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel von;
    private javax.swing.JButton zurueck;
    // End of variables declaration                   


}
