/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.klenze_kk.lingling.Gui;

import de.klenze_kk.lingling.Main;
import de.klenze_kk.lingling.logic.LogIn;

public class Register extends javax.swing.JPanel {

	/**
	 * Creates new form Register
	 */
	public Register() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">                          
	private void initComponents() {

		nutzername = new javax.swing.JLabel();
		passwort = new javax.swing.JLabel();
		nutzerText = new javax.swing.JTextField();
		passText1 = new javax.swing.JPasswordField();
		register = new javax.swing.JButton();
		zurueck = new javax.swing.JButton();
		passText2 = new javax.swing.JPasswordField();
		passwort1 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(800, 600));

		nutzername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		nutzername.setText("Nutzername: ");

		passwort.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		passwort.setText("Passwort: ");

		nutzerText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nutzerTextActionPerformed(evt);
			}
		});

		passText1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passText1ActionPerformed(evt);
			}
		});

		register.setBackground(new java.awt.Color(51, 204, 0));
		register.setForeground(new java.awt.Color(255, 255, 255));
		register.setText("Register");
		register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				registerActionPerformed(evt);
			}
		});

		zurueck.setBackground(new java.awt.Color(255, 51, 51));
		zurueck.setForeground(new java.awt.Color(255, 255, 255));
		zurueck.setText("Zurueck");
		zurueck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				zurueckActionPerformed(evt);
			}
		});

		passText2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passText2ActionPerformed(evt);
			}
		});

		passwort1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		passwort1.setText("Passwort bestätigen: ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(87, 87, 87)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(passwort1).addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(184, 184, 184).addComponent(zurueck,
												javax.swing.GroupLayout.PREFERRED_SIZE, 165,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(nutzername, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(passwort, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(nutzerText, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
										.addComponent(passText2, javax.swing.GroupLayout.DEFAULT_SIZE, 300,
												Short.MAX_VALUE)
										.addComponent(passText1, javax.swing.GroupLayout.Alignment.LEADING)))
								.addContainerGap(197, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(70, 70, 70).addComponent(nutzername).addGap(36, 36, 36)
				.addComponent(nutzerText, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(33, 33, 33).addComponent(passwort).addGap(37, 37, 37)
				.addComponent(passText1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(36, 36, 36).addComponent(passwort1).addGap(36, 36, 36)
				.addComponent(
						passText2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(57, 57, 57)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(zurueck, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(74, 74, 74)));
	}// </editor-fold>                        

	private void nutzerTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nutzerTextActionPerformed

	}// GEN-LAST:event_nutzerTextActionPerformed

	private void passText1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passText1ActionPerformed

	}// GEN-LAST:event_passText1ActionPerformed

	private void registerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registerActionPerformed
		String pass = new String(passText1.getPassword());
		if (!(pass.isEmpty() && nutzerText.getText().isEmpty() && passText2.getPassword().length == 0)) {
                     if((pass.isEmpty() && passText2.getPassword().length == 0) || nutzerText.getText().isEmpty() ){
                    Main.handleError("Eins der Felder ist Leer", false);
                    return;
                }
			if (pass.equals(new String(passText2.getPassword())))
				Main.getDatabaseManager().registerUser(new LogIn(true), nutzerText.getText(), pass);
			else
				Main.handleError("Passwoerter sind nicht gleich", false);
		}
	}// GEN-LAST:event_registerActionPerformed

	private void zurueckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_zurueckActionPerformed
		Main.setJPanel(new LogScreen2());
	}// GEN-LAST:event_zurueckActionPerformed

	private void passText2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passText2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_passText2ActionPerformed

	// Variables declaration - do not modify                     
	private javax.swing.JTextField nutzerText;
	private javax.swing.JLabel nutzername;
	private javax.swing.JPasswordField passText1;
	private javax.swing.JPasswordField passText2;
	private javax.swing.JLabel passwort;
	private javax.swing.JLabel passwort1;
	private javax.swing.JButton register;
	private javax.swing.JButton zurueck;
	// End of variables declaration                   
}
